FinalProject/Areas/Server/Controllers/ManagerReportController.cs
using Microsoft.AspNetCore.Mvc;
using FinalProject.Models;
using FinalProject.Areas.Server.Models;
using FinalProject.Areas.Server.ViewModels;
using static FinalProject.Models.CGlobalParameters;
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.Hosting;

namespace FinalProject.Areas.Server.Controllers.Controllers
{
    [Area("Server")]
    public class ManagerReportController : SuperController
    {
        private readonly FinalProjectContext _context;
        public ManagerReportController(FinalProjectContext context)
        {
            _context = context;
        }

        public IActionResult List()
        {
            List<CManagerReportViewModel> model = new List<CManagerReportViewModel>();
            var datas = (from productReport in _context.TProductReport
                         join orderDetail in _context.TOrderDetail on productReport.FOrderDetailId equals orderDetail.FId
                         join customerSheet in _context.TCustomerOrderSheet on orderDetail.FCustomerOrderSheetId equals customerSheet.FId
                         join customer in _context.TCustomer on customerSheet.FCustomerId equals customer.FId
                         join product in _context.TProduct on orderDetail.FProductId equals product.FId
                         join provider in _context.TProvider on product.FProviderId equals provider.FId
                         where !product.FRemoved
                         select new
                         {
                             ReportID = productReport.FId,
                             ProductName = product.FName,
                             ProductProvider = provider.FCompanyName,
                             ReportContent = productReport.FReportContent,
                             CreateDateTime = productReport.FCreationDate
                         }).ToList();
            foreach (var item in datas)
            {
                model.Add(new CManagerReportViewModel()
                {
                    ReportID = item.ReportID,
                    ProductName = item.ProductName,
                    ProductProvider = item.ProductProvider,
                    ReportContent = item.ReportContent,
                    CreateDateTime = item.CreateDateTime
                });
            }
            return View(model);
        }

        public IActionResult Details(int? id)
        {
            List<CManagerReportViewModel> model = new List<CManagerReportViewModel>();
            if (id != null)
            {
                var datas = (from productReport in _context.TProductReport
                             join orderDetail in _context.TOrderDetail on productReport.FOrderDetailId equals orderDetail.FId
                             join customerSheet in _context.TCustomerOrderSheet on orderDetail.FCustomerOrderSheetId equals customerSheet.FId
                             join customer in _context.TCustomer on customerSheet.FCustomerId equals customer.FId
                             join product in _context.TProduct on orderDetail.FProductId equals product.FId
                             join provider in _context.TProvider on product.FProviderId equals provider.FId
                             where productReport.FId == id
                             select new
                             {
                                 ReportID = productReport.FId,
                                 ProductProviderID = provider.FId,
                                 ProductProvider = provider.FCompanyName,
                                 ProductProviderTel = provider.FContactTel,
                                 ProductProviderMobile = provider.FContactMobile,
                                 ProductProviderEmail = provider.FContactEmail,
                                 ProductID = product.FId,
                                 ProductName = product.FName,
                                 ProductDescription = product.FDescription,
                                 ProductPoint = product.FAssemblyPoint,
                                 ProductRemark = product.FRemark,
                                 CustomerID = customer.FId,
                                 CustomerLastName = customer.FLastName,
                                 CustomerFirstName = customer.FFirstName,
                                 CustomerTel = customer.FTel,
                                 CustomerMobile = customer.FMobile,
                                 CustomerEmail = customer.FEmail,
                                 ReportContent = productReport.FReportContent,
                                 CreateDateTime = productReport.FCreationDate
                             }).ToList();
                foreach (var item in datas)
                {
                    model.Add(new CManagerReportViewModel()
                    {
                        ReportID = item.ReportID,
                        ProductProviderID = item.ProductProviderID,
                        ProductProvider = item.ProductProvider,
                        ProductProviderTel = item.ProductProviderTel,
                        ProductProviderMobile = item.ProductProviderMobile,
                        ProductProviderEmail = item.ProductProviderEmail,
                        ProductID = item.ProductID,
                        ProductName = item.ProductName,
                        ProductDescription = item.ProductDescription,
                        ProductPoint = item.ProductPoint,
                        ProductRemark = item.ProductRemark,
                        CustomerID = item.CustomerID,
                        CustomerLastName = item.CustomerLastName,
                        CustomerFirstName = item.CustomerFirstName,
                        CustomerTel = item.CustomerTel,
                        CustomerMobile = item.CustomerMobile,
                        CustomerEmail = item.CustomerEmail,
                        ReportContent = item.ReportContent,
                        CreateDateTime = item.CreateDateTime
                    });
                }
                return View(model[0]);
            }
            return RedirectToAction("List");
        }
        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                TProductReview delReview = _context.TProductReview.FirstOrDefault(t => t.FId == id);
                if (delReview != null)
                {
                    _context.TProductReview.Remove(delReview);
                    _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("List");
        }

    }

}

FinalProject/Areas/Server/Views/ManagerReport/Details.cshtml
@model FinalProject.Areas.Server.ViewModels.CManagerReportViewModel

@{
    ViewData["Title"] = "檢舉詳細資料";
}

<div class="container-fluid px-4">
    <h1 class="mt-4">
        檢舉詳細資料
    </h1>
</div>
<div class="card mb-4">
    <div class="card-body">
        <div>
            <dl class="row ms-2">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ReportID)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ReportID)
                </dd>
            </dl>
            <hr />
            <dl class="row ms-2">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductID)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductID)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductProviderID)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductProviderID)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductProvider)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductProvider)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductProviderTel)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductProviderTel)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductProviderMobile)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductProviderMobile)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductProviderEmail)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductProviderEmail)
                </dd>
            </dl>
            <hr />
            <dl class="row ms-2">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CustomerID)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CustomerID)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CustomerLastName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CustomerLastName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CustomerFirstName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CustomerFirstName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CustomerTel)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CustomerTel)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CustomerMobile)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CustomerMobile)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CustomerEmail)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CustomerEmail)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ReportContent)
                </dt>
                <dd class="col-sm-10">
                    @Html.Raw(Model.ReportContent.Replace(Environment.NewLine, "<br/>"))
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CreateDateTime)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CreateDateTime)
                </dd>
            </dl>
        </div>
        <hr />
        <div>
            <a asp-action="List" class="btn btn-danger">返回</a>
        </div>
    </div>
</div>

FinalProject/Areas/Server/Views/ManagerReport/List.cshtml
@model IEnumerable<FinalProject.Areas.Server.ViewModels.CManagerReportViewModel>

@{
    ViewData["Title"] = "檢舉管理";
}

<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">
            檢舉管理
        </h1>
    </div>
    <div class="card mb-4">
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>
                            序號
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ReportID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProductName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProductProvider)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ReportContent)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CreateDateTime)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int count = 0;
                        foreach (var item in Model)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ReportID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ProductName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ProductProvider)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ReportContent)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreateDateTime)
                                </td>
                                <td>

                                    @Html.ActionLink("詳細", "Details", new {id=item.ReportID },new { @class="btn btn-secondary"})
                                    @Html.ActionLink("刪除", "Delete","ManagerReport", new {  id=item.ReportID  },new{onclick = "return confirm('確定刪除?')",Class="btn btn-danger"})
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</main>